### ISSUE TITLE
All playlist items repeat (Ver 1.01)

### ISSUE THREAD

**Issue by Steve-Palmer** [starplayerpc/starplayerpc#17]
In version 1.01, all playlist items repeat regardless of the setting of the Repeat switch.

**Comment by isedwards** [comment]
This is a new bug, introduced by the playlist file now having more than two columns and the `string.gmatch` regular expression only matching the first separator character.

**Comment by isedwards** [comment]
Turns out there was a second bug introduced by refactoring and extracting set_repeat into it's own function. Fixed now.
