### ISSUE TITLE
Add a circle to the splash screen

### ISSUE THREAD

**Issue by Steve-Palmer** [starplayerpc/starplayerpc#18]
Add a circle to the 16x9 splash screen to give a visual indication that the playback and final recording is in the correct mode, and not distorted by using the wrong aspect ratio. File is sppmain.png

**Comment by isedwards** [comment]
![sppmain](https://user-images.githubusercontent.com/2097922/28248577-a535ffde-6a3e-11e7-9f74-88f1e0c5410e.png)
