### ISSUE TITLE
Play and pause option

### ISSUE THREAD

**Issue by isedwards** [starplayerpc/starplayerpc#3]
Add an option to play a clip and then freeze (pause) on final frame until user manually advances.

Requires a menu to be displayed when right-clicking.

**Comment by isedwards** [comment]
Is this capability still required (pause/freezing will not show any animations)?

**Comment by Steve-Palmer** [comment]
The old WeatherEye/Starplayer always produced a 1-second clip for looping, even if it had no animations. It would be possible for e.g. headline boxes where the appearance of the box and text is animated, but they are then static. However, the risk of this technique being used by mistake when there are animated symbols is probably too high, so better to loop on the last second until the click - see #4 - and not freeze.
